#!/usr/bin/env python3
"""
Snowflake Generic Data Platform — One-time Initialization Script

Creates the complete Snowflake structure for the platform:
  - Four databases: GENERIC_AIRBYTE_LANDING, GENERIC_BRONZE, GENERIC_SILVER, GENERIC_PLATFORM
  - Two warehouses: PLATFORM_WH (shared), ANALYST_WH
  - Four RBAC roles with hierarchy and full privilege grants
  - Two service users: PLATFORM_SVC (admin) and AIRBYTE_USER (loader)
  - Schema registry, source catalog, and run log tables
  - Nightly cleanup task for the landing zone

Run once as ACCOUNTADMIN (or SECURITYADMIN + SYSADMIN).
Safe to re-run — uses IF NOT EXISTS throughout.

Usage:
  python sgdp/scripts/init_snowflake.py

Required environment variables:
  SNOWFLAKE_ACCOUNT         e.g. abc12345.us-east-1
  SNOWFLAKE_USER            your personal admin username
  SNOWFLAKE_PASSWORD        your personal admin password
  PLATFORM_SVC_PASSWORD     password for the PLATFORM_SVC service account
  AIRBYTE_PASSWORD          password for the AIRBYTE_USER service account

Optional:
  SNOWFLAKE_ROLE            role to connect with (default: ACCOUNTADMIN)
  SNOWFLAKE_WAREHOUSE       bootstrap warehouse — can be any existing WH (default: PLATFORM_WH)
  PLATFORM_SVC_USER         service account username (default: PLATFORM_SVC)
  AIRBYTE_USERNAME          Airbyte service account username (default: AIRBYTE_USER)
"""

import os
import sys

try:
    import snowflake.connector
except ImportError:
    print("❌ snowflake-connector-python not installed. Run: pip install snowflake-connector-python")
    sys.exit(1)

# ──────────────────────────────────────────────────────────────────────────────
# Configuration
# ──────────────────────────────────────────────────────────────────────────────

ACCOUNT   = os.getenv("SNOWFLAKE_ACCOUNT")
USER      = os.getenv("SNOWFLAKE_USER")
PASSWORD  = os.getenv("SNOWFLAKE_PASSWORD")
ROLE      = os.getenv("SNOWFLAKE_ROLE", "ACCOUNTADMIN")
WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE", "PLATFORM_WH")

PLATFORM_SVC_USER     = os.getenv("PLATFORM_SVC_USER", "PLATFORM_SVC")
PLATFORM_SVC_PASSWORD = os.getenv("PLATFORM_SVC_PASSWORD")
AIRBYTE_USERNAME      = os.getenv("AIRBYTE_USERNAME", "AIRBYTE_USER")
AIRBYTE_PASSWORD      = os.getenv("AIRBYTE_PASSWORD")

missing = []
if not ACCOUNT:           missing.append("SNOWFLAKE_ACCOUNT")
if not USER:              missing.append("SNOWFLAKE_USER")
if not PASSWORD:          missing.append("SNOWFLAKE_PASSWORD")
if not PLATFORM_SVC_PASSWORD: missing.append("PLATFORM_SVC_PASSWORD")
if not AIRBYTE_PASSWORD:  missing.append("AIRBYTE_PASSWORD")

if missing:
    print("❌ Missing required environment variables:")
    for var in missing:
        print(f"   {var}")
    print("\n   Example (PowerShell):")
    print("   $env:SNOWFLAKE_ACCOUNT          = 'abc12345.us-east-1'")
    print("   $env:SNOWFLAKE_USER             = 'my_admin'")
    print("   $env:SNOWFLAKE_PASSWORD         = 'my_password'")
    print("   $env:PLATFORM_SVC_PASSWORD      = 'secure_password'")
    print("   $env:AIRBYTE_PASSWORD           = 'secure_password'")
    sys.exit(1)

# Escape single quotes in passwords to prevent SQL errors
_psvc = PLATFORM_SVC_PASSWORD.replace("'", "\\'")
_airb = AIRBYTE_PASSWORD.replace("'", "\\'")

# ──────────────────────────────────────────────────────────────────────────────
# SQL Statements
# ──────────────────────────────────────────────────────────────────────────────

SQL_STATEMENTS = [

    # ── Databases ──────────────────────────────────────────────────────────────
    "USE ROLE SYSADMIN",

    "CREATE DATABASE IF NOT EXISTS GENERIC_AIRBYTE_LANDING COMMENT = 'Airbyte landing zone — raw data from sources'",
    "CREATE DATABASE IF NOT EXISTS GENERIC_BRONZE          COMMENT = 'Thin transformation layer — generated by platform'",
    "CREATE DATABASE IF NOT EXISTS GENERIC_SILVER          COMMENT = 'Business-ready layer — generated by platform'",
    "CREATE DATABASE IF NOT EXISTS GENERIC_PLATFORM        COMMENT = 'Generic platform metadata and catalog'",

    # Disable FAIL_SAFE on landing — data preserved in BRONZE/SILVER
    "ALTER DATABASE GENERIC_AIRBYTE_LANDING SET DATA_RETENTION_TIME_IN_DAYS = 0",

    # ── Warehouses ─────────────────────────────────────────────────────────────
    "CREATE WAREHOUSE IF NOT EXISTS PLATFORM_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60  AUTO_RESUME = TRUE COMMENT = 'All platform operations: Airbyte loading, dbt transforms, catalog services'",
    "CREATE WAREHOUSE IF NOT EXISTS ANALYST_WH  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Analyst queries on SILVER layer'",

    # ── Roles ──────────────────────────────────────────────────────────────────
    "USE ROLE SECURITYADMIN",

    "CREATE ROLE IF NOT EXISTS PLATFORM_ADMIN   COMMENT = 'Full platform access: read/write all databases'",
    "CREATE ROLE IF NOT EXISTS LOADER_ROLE      COMMENT = 'Airbyte: write to GENERIC_AIRBYTE_LANDING only'",
    "CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE COMMENT = 'dbt: read landing, write BRONZE + SILVER'",
    "CREATE ROLE IF NOT EXISTS ANALYST_ROLE     COMMENT = 'Analysts: read SILVER only'",

    # Hierarchy: all roles roll up to SYSADMIN for manageability
    "GRANT ROLE PLATFORM_ADMIN   TO ROLE SYSADMIN",
    "GRANT ROLE LOADER_ROLE      TO ROLE PLATFORM_ADMIN",
    "GRANT ROLE TRANSFORMER_ROLE TO ROLE PLATFORM_ADMIN",
    "GRANT ROLE ANALYST_ROLE     TO ROLE PLATFORM_ADMIN",

    # ── Service Users ──────────────────────────────────────────────────────────
    f"CREATE USER IF NOT EXISTS {PLATFORM_SVC_USER} PASSWORD = '{_psvc}' DEFAULT_ROLE = 'PLATFORM_ADMIN' DEFAULT_WAREHOUSE = 'PLATFORM_WH' COMMENT = 'Platform admin service account'",
    f"GRANT ROLE PLATFORM_ADMIN TO USER {PLATFORM_SVC_USER}",

    f"CREATE USER IF NOT EXISTS {AIRBYTE_USERNAME} PASSWORD = '{_airb}' DEFAULT_ROLE = 'LOADER_ROLE' DEFAULT_WAREHOUSE = 'PLATFORM_WH' COMMENT = 'Airbyte service account — writes to GENERIC_AIRBYTE_LANDING'",
    f"GRANT ROLE LOADER_ROLE TO USER {AIRBYTE_USERNAME}",

    # ── Warehouse Grants ───────────────────────────────────────────────────────
    "USE ROLE SYSADMIN",

    "GRANT USAGE ON WAREHOUSE PLATFORM_WH TO ROLE PLATFORM_ADMIN",
    "GRANT USAGE ON WAREHOUSE PLATFORM_WH TO ROLE LOADER_ROLE",
    "GRANT USAGE ON WAREHOUSE PLATFORM_WH TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON WAREHOUSE ANALYST_WH  TO ROLE ANALYST_ROLE",

    # ── Database Grants ────────────────────────────────────────────────────────
    "GRANT ALL PRIVILEGES ON DATABASE GENERIC_AIRBYTE_LANDING TO ROLE PLATFORM_ADMIN",
    "GRANT ALL PRIVILEGES ON DATABASE GENERIC_BRONZE          TO ROLE PLATFORM_ADMIN",
    "GRANT ALL PRIVILEGES ON DATABASE GENERIC_SILVER          TO ROLE PLATFORM_ADMIN",
    "GRANT ALL PRIVILEGES ON DATABASE GENERIC_PLATFORM        TO ROLE PLATFORM_ADMIN",

    "GRANT USAGE         ON DATABASE GENERIC_AIRBYTE_LANDING TO ROLE LOADER_ROLE",
    "GRANT CREATE SCHEMA ON DATABASE GENERIC_AIRBYTE_LANDING TO ROLE LOADER_ROLE",

    "GRANT USAGE ON DATABASE GENERIC_AIRBYTE_LANDING TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON DATABASE GENERIC_BRONZE          TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON DATABASE GENERIC_SILVER          TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON DATABASE GENERIC_PLATFORM        TO ROLE TRANSFORMER_ROLE",

    "GRANT USAGE ON DATABASE GENERIC_SILVER TO ROLE ANALYST_ROLE",

    # ── Schema Grants ──────────────────────────────────────────────────────────
    # LOADER_ROLE: write to landing
    "GRANT USAGE          ON SCHEMA GENERIC_AIRBYTE_LANDING.PUBLIC               TO ROLE LOADER_ROLE",
    "GRANT CREATE TABLE   ON ALL    SCHEMAS IN DATABASE GENERIC_AIRBYTE_LANDING   TO ROLE LOADER_ROLE",
    "GRANT CREATE TABLE   ON FUTURE SCHEMAS IN DATABASE GENERIC_AIRBYTE_LANDING   TO ROLE LOADER_ROLE",
    "GRANT INSERT, UPDATE ON ALL    TABLES  IN DATABASE GENERIC_AIRBYTE_LANDING   TO ROLE LOADER_ROLE",
    "GRANT INSERT, UPDATE ON FUTURE TABLES  IN DATABASE GENERIC_AIRBYTE_LANDING   TO ROLE LOADER_ROLE",
    "GRANT CREATE STAGE   ON SCHEMA GENERIC_AIRBYTE_LANDING.PUBLIC               TO ROLE LOADER_ROLE",
    "GRANT SELECT         ON ALL    TABLES  IN DATABASE GENERIC_AIRBYTE_LANDING   TO ROLE LOADER_ROLE",
    "GRANT SELECT         ON FUTURE TABLES  IN DATABASE GENERIC_AIRBYTE_LANDING   TO ROLE LOADER_ROLE",

    # TRANSFORMER_ROLE: read landing, write bronze + silver, read platform metadata
    "GRANT USAGE ON SCHEMA GENERIC_PLATFORM.PUBLIC TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON SCHEMA GENERIC_BRONZE.PUBLIC   TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON SCHEMA GENERIC_SILVER.PUBLIC   TO ROLE TRANSFORMER_ROLE",

    "GRANT SELECT ON ALL    TABLES IN DATABASE GENERIC_AIRBYTE_LANDING TO ROLE TRANSFORMER_ROLE",
    "GRANT SELECT ON FUTURE TABLES IN DATABASE GENERIC_AIRBYTE_LANDING TO ROLE TRANSFORMER_ROLE",

    "GRANT CREATE TABLE   ON ALL    SCHEMAS IN DATABASE GENERIC_BRONZE TO ROLE TRANSFORMER_ROLE",
    "GRANT CREATE TABLE   ON FUTURE SCHEMAS IN DATABASE GENERIC_BRONZE TO ROLE TRANSFORMER_ROLE",
    "GRANT INSERT, UPDATE ON ALL    TABLES  IN DATABASE GENERIC_BRONZE TO ROLE TRANSFORMER_ROLE",
    "GRANT INSERT, UPDATE ON FUTURE TABLES  IN DATABASE GENERIC_BRONZE TO ROLE TRANSFORMER_ROLE",

    "GRANT CREATE TABLE   ON ALL    SCHEMAS IN DATABASE GENERIC_SILVER TO ROLE TRANSFORMER_ROLE",
    "GRANT CREATE TABLE   ON FUTURE SCHEMAS IN DATABASE GENERIC_SILVER TO ROLE TRANSFORMER_ROLE",
    "GRANT INSERT, UPDATE ON ALL    TABLES  IN DATABASE GENERIC_SILVER TO ROLE TRANSFORMER_ROLE",
    "GRANT INSERT, UPDATE ON FUTURE TABLES  IN DATABASE GENERIC_SILVER TO ROLE TRANSFORMER_ROLE",

    # ANALYST_ROLE: read silver
    "GRANT USAGE  ON SCHEMA GENERIC_SILVER.PUBLIC TO ROLE ANALYST_ROLE",
    "GRANT SELECT ON ALL    TABLES IN DATABASE GENERIC_SILVER TO ROLE ANALYST_ROLE",
    "GRANT SELECT ON FUTURE TABLES IN DATABASE GENERIC_SILVER TO ROLE ANALYST_ROLE",

    # ── Platform Metadata Tables ───────────────────────────────────────────────
    "USE ROLE SYSADMIN",
    "USE DATABASE GENERIC_PLATFORM",
    "USE SCHEMA PUBLIC",

    """CREATE TABLE IF NOT EXISTS schema_registry (
        id                      VARCHAR         NOT NULL DEFAULT uuid_string(),
        source_name             VARCHAR         NOT NULL,
        table_name              VARCHAR         NOT NULL,
        columns                 VARIANT         NOT NULL COMMENT 'JSON: [{name, type, nullable}]',
        primary_keys            VARIANT                  COMMENT 'JSON array of PK column names',
        load_strategy           VARCHAR                  COMMENT 'incremental | full_refresh | scd2',
        schema_hash             VARCHAR                  COMMENT 'MD5 of sorted column list',
        is_active               BOOLEAN         DEFAULT TRUE,
        business_owner          VARCHAR                  COMMENT 'Team or email for alerts',
        airbyte_connection_id   VARCHAR,
        first_seen_at           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
        last_seen_at            TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
        last_changed_at         TIMESTAMP_NTZ            COMMENT 'When schema last changed',
        change_history          VARIANT                  COMMENT 'JSON array of past schema states',
        PRIMARY KEY (source_name, table_name),
        CONSTRAINT schema_registry_uk UNIQUE (id)
    ) COMMENT = 'Platform metadata: all active sources and their schemas'""",

    """CREATE TABLE IF NOT EXISTS source_catalog (
        source_name             VARCHAR         NOT NULL PRIMARY KEY,
        airbyte_connection_id   VARCHAR         NOT NULL UNIQUE,
        sync_schedule           VARCHAR                  COMMENT 'Cron expression for sync timing',
        bronze_schema           VARCHAR                  COMMENT 'Schema for bronze models',
        silver_schema           VARCHAR                  COMMENT 'Schema for silver models',
        business_owner          VARCHAR                  COMMENT 'Team or email for ownership and alerts',
        slack_alert_channel     VARCHAR,
        is_active               BOOLEAN         DEFAULT TRUE,
        created_at              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
        last_synced_at          TIMESTAMP_NTZ,
        model_generation_status VARCHAR                  COMMENT 'pending | generated | error'
    ) COMMENT = 'Source registry: Airbyte connections and sync metadata'""",

    """CREATE TABLE IF NOT EXISTS run_log (
        run_id              VARCHAR         NOT NULL DEFAULT uuid_string() PRIMARY KEY,
        source_name         VARCHAR         NOT NULL,
        dag_run_id          VARCHAR,
        airbyte_job_id      VARCHAR,
        dbt_run_status      VARCHAR                  COMMENT 'success | error | partial',
        rows_loaded_bronze  NUMBER,
        rows_loaded_silver  NUMBER,
        schema_changes      VARIANT                  COMMENT 'JSON diff from this run',
        started_at          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
        completed_at        TIMESTAMP_NTZ,
        duration_seconds    NUMBER,
        created_at          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
    ) COMMENT = 'Pipeline execution history and metrics'""",

    # ── Cleanup Task ───────────────────────────────────────────────────────────
    """CREATE OR REPLACE TASK GENERIC_PLATFORM.PUBLIC.cleanup_old_landing_data
        WAREHOUSE = PLATFORM_WH
        SCHEDULE  = 'USING CRON 0 2 * * * UTC'
        COMMENT   = 'Delete landing zone records > 30 days old (data preserved in BRONZE/SILVER)'
    AS
        DELETE FROM GENERIC_AIRBYTE_LANDING.PUBLIC.airbyte_raw
        WHERE _airbyte_loaded_at < CURRENT_DATE - 30""",

    "ALTER TASK GENERIC_PLATFORM.PUBLIC.cleanup_old_landing_data RESUME",
]

# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def init_snowflake():
    print(f"🔗 Connecting to Snowflake: {ACCOUNT} as {USER} (role: {ROLE})...")

    try:
        conn = snowflake.connector.connect(
            account=ACCOUNT,
            user=USER,
            password=PASSWORD,
            role=ROLE,
            # Warehouse may not exist yet on first run — omit to avoid error
            warehouse=WAREHOUSE if WAREHOUSE != "PLATFORM_WH" else None,
        )
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        print(f"\n   Check: SNOWFLAKE_ACCOUNT={ACCOUNT}, SNOWFLAKE_USER={USER}, SNOWFLAKE_ROLE={ROLE}")
        sys.exit(1)

    print("✅ Connected\n")
    cursor = conn.cursor()
    executed = 0
    failed = 0

    for i, sql in enumerate(SQL_STATEMENTS, 1):
        label = " ".join(sql.split())[:70]
        try:
            cursor.execute(sql)
            print(f"  [{i:2d}/{len(SQL_STATEMENTS)}] ✅  {label}...")
            executed += 1
        except Exception as e:
            print(f"  [{i:2d}/{len(SQL_STATEMENTS)}] ⚠️   {label}... ({str(e)[:60]})")
            failed += 1

    conn.close()

    print(f"\n{'='*72}")
    print(f"  Done: {executed} succeeded, {failed} warnings")
    print(f"{'='*72}")

    if failed == 0:
        print("\n✅ Snowflake platform is ready!")
    else:
        print("\n⚠️  Some statements had warnings (likely already exist — this is OK on re-runs)")

    print(f"""
  Service accounts created:
    {PLATFORM_SVC_USER}  →  PLATFORM_ADMIN  /  PLATFORM_WH
    {AIRBYTE_USERNAME}    →  LOADER_ROLE     /  PLATFORM_WH

  Next steps:
    1. Connect Airbyte to Snowflake using {AIRBYTE_USERNAME} / LOADING into GENERIC_AIRBYTE_LANDING
    2. Register your first source in GENERIC_PLATFORM.PUBLIC.source_catalog
    3. Start the stack: docker compose -f compose/docker-compose.yml up -d
""")


if __name__ == "__main__":
    init_snowflake()
