#!/usr/bin/env python3
"""
Snowflake Generic Data Platform — One-time Initialization Script

Creates the complete Snowflake schema structure for the platform:
  - Four databases: RAW, BRONZE, SILVER, PLATFORM
  - Schema registry and source catalog tables
  - Warehouses with auto-suspend settings
  - RBAC roles and grants
  - Run log table for pipeline observability

Run once, then safe to re-run (idempotent where possible).

Usage:
  python platform/scripts/init_snowflake.py

Environment variables required:
  SNOWFLAKE_ACCOUNT      e.g. abc12345.us-east-1
  SNOWFLAKE_USER         service account username
  SNOWFLAKE_PASSWORD     service account password
  SNOWFLAKE_ROLE         admin role (e.g. PLATFORM_ADMIN)
  SNOWFLAKE_WAREHOUSE    admin warehouse (e.g. PLATFORM_WH)
"""

import os
import sys
from pathlib import Path

try:
    import snowflake.connector
except ImportError:
    print("❌ snowflake-connector-python not installed. Run: pip install snowflake-connector-python")
    sys.exit(1)

# ──────────────────────────────────────────────────────────────────────────────
# Configuration
# ──────────────────────────────────────────────────────────────────────────────

ACCOUNT = os.getenv("SNOWFLAKE_ACCOUNT")
USER = os.getenv("SNOWFLAKE_USER")
PASSWORD = os.getenv("SNOWFLAKE_PASSWORD")
ROLE = os.getenv("SNOWFLAKE_ROLE", "PLATFORM_ADMIN")
WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE", "PLATFORM_WH")

# Validation
if not all([ACCOUNT, USER, PASSWORD]):
    print("❌ Missing Snowflake credentials:")
    print("   Set: SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, SNOWFLAKE_PASSWORD")
    print("\n   Example:")
    print("   $env:SNOWFLAKE_ACCOUNT = 'abc12345.us-east-1'")
    print("   $env:SNOWFLAKE_USER = 'platform_svc'")
    print("   $env:SNOWFLAKE_PASSWORD = 'your_password'")
    sys.exit(1)

# ──────────────────────────────────────────────────────────────────────────────
# SQL Statements
# ──────────────────────────────────────────────────────────────────────────────

SQL_STATEMENTS = [
    # Databases (namespaced for shared Snowflake account)
    "CREATE DATABASE IF NOT EXISTS GENERIC_AIRBYTE_LANDING COMMENT = 'Airbyte landing zone — raw data from sources'",
    "CREATE DATABASE IF NOT EXISTS GENERIC_BRONZE COMMENT = 'Thin transformation layer — generated by platform'",
    "CREATE DATABASE IF NOT EXISTS GENERIC_SILVER COMMENT = 'Business-ready layer — generated by platform'",
    "CREATE DATABASE IF NOT EXISTS GENERIC_PLATFORM COMMENT = 'Generic platform metadata and catalog'",

    # Disable FAIL_SAFE on landing database to reduce storage costs (data preserved in BRONZE/SILVER)
    "ALTER DATABASE GENERIC_AIRBYTE_LANDING SET DATA_RETENTION_TIME_IN_DAYS = 0",

    # Warehouses
    "CREATE WAREHOUSE IF NOT EXISTS PLATFORM_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE COMMENT = 'Platform services: catalog syncer, model generator'",
    "CREATE WAREHOUSE IF NOT EXISTS LOADING_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE COMMENT = 'Airbyte data loading'",
    "CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MAX_CONCURRENCY_LEVEL = 3 COMMENT = 'dbt transformations (limited concurrency)'",
    "CREATE WAREHOUSE IF NOT EXISTS ANALYST_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Analyst queries on SILVER layer'",

    # Roles
    "CREATE ROLE IF NOT EXISTS PLATFORM_ADMIN COMMENT = 'Full platform access: read/write all databases'",
    "CREATE ROLE IF NOT EXISTS LOADER_ROLE COMMENT = 'Airbyte: write to RAW only'",
    "CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE COMMENT = 'dbt: read RAW, write BRONZE + SILVER'",
    "CREATE ROLE IF NOT EXISTS ANALYST_ROLE COMMENT = 'Analysts: read SILVER only'",

    # Role assignments (grant current user as PLATFORM_ADMIN)
    f"GRANT ROLE PLATFORM_ADMIN TO USER {USER}",

    # Warehouse grants
    "GRANT USAGE ON WAREHOUSE PLATFORM_WH TO ROLE PLATFORM_ADMIN",
    "GRANT USAGE ON WAREHOUSE LOADING_WH TO ROLE LOADER_ROLE",
    "GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE ANALYST_ROLE",

    # Database grants
    "GRANT ALL PRIVILEGES ON DATABASE GENERIC_AIRBYTE_LANDING TO ROLE PLATFORM_ADMIN",
    "GRANT ALL PRIVILEGES ON DATABASE GENERIC_BRONZE TO ROLE PLATFORM_ADMIN",
    "GRANT ALL PRIVILEGES ON DATABASE GENERIC_SILVER TO ROLE PLATFORM_ADMIN",
    "GRANT ALL PRIVILEGES ON DATABASE GENERIC_PLATFORM TO ROLE PLATFORM_ADMIN",

    "GRANT USAGE ON DATABASE GENERIC_AIRBYTE_LANDING TO ROLE LOADER_ROLE",
    "GRANT USAGE ON DATABASE GENERIC_BRONZE TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON DATABASE GENERIC_SILVER TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON DATABASE GENERIC_PLATFORM TO ROLE TRANSFORMER_ROLE",

    "GRANT USAGE ON DATABASE GENERIC_SILVER TO ROLE ANALYST_ROLE",

    # Schema grants (public schema in each database)
    "GRANT USAGE ON SCHEMA GENERIC_AIRBYTE_LANDING.PUBLIC TO ROLE LOADER_ROLE",
    "GRANT USAGE ON SCHEMA GENERIC_PLATFORM.PUBLIC TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON SCHEMA GENERIC_BRONZE.PUBLIC TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON SCHEMA GENERIC_SILVER.PUBLIC TO ROLE TRANSFORMER_ROLE",
    "GRANT USAGE ON SCHEMA GENERIC_SILVER.PUBLIC TO ROLE ANALYST_ROLE",

    # Schema Registry Table (GENERIC_PLATFORM.PUBLIC.schema_registry)
    """
    CREATE TABLE IF NOT EXISTS GENERIC_PLATFORM.PUBLIC.schema_registry (
        id                      VARCHAR     NOT NULL DEFAULT uuid_string(),
        source_name             VARCHAR     NOT NULL,
        table_name              VARCHAR     NOT NULL,
        columns                 VARIANT     NOT NULL COMMENT 'JSON: [{name, type, nullable}]',
        primary_keys            ARRAY       COMMENT 'List of PK column names',
        load_strategy           VARCHAR     COMMENT 'incremental | full_refresh | scd2',
        schema_hash             VARCHAR     COMMENT 'MD5 of sorted column list',
        is_active               BOOLEAN     DEFAULT TRUE,
        business_owner          VARCHAR     COMMENT 'Team or email for alerts',
        airbyte_connection_id   VARCHAR,
        first_seen_at           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        last_seen_at            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        last_changed_at         TIMESTAMP_NTZ COMMENT 'When schema last changed',
        change_history          VARIANT     COMMENT 'JSON array of past schema states',
        PRIMARY KEY (source_name, table_name),
        CONSTRAINT schema_registry_uk UNIQUE (id)
    )
    COMMENT = 'Platform metadata: all active sources and their schemas'
    """,

    # Source Catalog Table (GENERIC_PLATFORM.PUBLIC.source_catalog)
    """
    CREATE TABLE IF NOT EXISTS GENERIC_PLATFORM.PUBLIC.source_catalog (
        source_name             VARCHAR     NOT NULL PRIMARY KEY,
        airbyte_connection_id   VARCHAR     NOT NULL UNIQUE,
        sync_schedule           VARCHAR     COMMENT 'Cron expression for sync timing',
        bronze_schema           VARCHAR     DEFAULT source_name() COMMENT 'Schema for bronze models',
        silver_schema           VARCHAR     DEFAULT source_name() COMMENT 'Schema for silver models',
        business_owner          VARCHAR     COMMENT 'Team or email for ownership and alerts',
        slack_alert_channel     VARCHAR,
        is_active               BOOLEAN     DEFAULT TRUE,
        created_at              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        last_synced_at          TIMESTAMP_NTZ,
        model_generation_status VARCHAR     COMMENT 'pending | generated | error'
    )
    COMMENT = 'Source registry: Airbyte connections and sync metadata'
    """,

    # Run Log Table (GENERIC_PLATFORM.PUBLIC.run_log)
    """
    CREATE TABLE IF NOT EXISTS GENERIC_PLATFORM.PUBLIC.run_log (
        run_id              VARCHAR         NOT NULL DEFAULT uuid_string() PRIMARY KEY,
        source_name         VARCHAR         NOT NULL,
        dag_run_id          VARCHAR,
        airbyte_job_id      VARCHAR,
        dbt_run_status      VARCHAR         COMMENT 'success | error | partial',
        rows_loaded_bronze  NUMBER,
        rows_loaded_silver  NUMBER,
        schema_changes      VARIANT         COMMENT 'JSON diff from this run',
        started_at          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
        completed_at        TIMESTAMP_NTZ,
        duration_seconds    NUMBER,
        created_at          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
    )
    COMMENT = 'Pipeline execution history and metrics'
    """,

    # Cleanup task: Delete landing data older than 30 days (saves storage, keeps incremental window)
    """
    CREATE OR REPLACE TASK GENERIC_PLATFORM.PUBLIC.cleanup_old_landing_data
    WAREHOUSE = PLATFORM_WH
    SCHEDULE = 'USING CRON 0 2 * * * UTC'
    COMMENT = 'Delete landing zone records > 30 days old (data preserved in BRONZE/SILVER)'
    AS
    CALL SYSTEM$EXECUTE_IMMEDIATE(
        'DELETE FROM GENERIC_AIRBYTE_LANDING.public.airbyte_raw WHERE _airbyte_loaded_at < CURRENT_DATE - 30'
    )
    """,

    # Enable the cleanup task
    "ALTER TASK GENERIC_PLATFORM.PUBLIC.cleanup_old_landing_data RESUME",
]

# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def init_snowflake():
    """Execute initialization SQL against Snowflake."""
    print(f"🔗 Connecting to Snowflake: {ACCOUNT} as {USER}...")

    try:
        conn = snowflake.connector.connect(
            account=ACCOUNT,
            user=USER,
            password=PASSWORD,
            role=ROLE,
            warehouse=WAREHOUSE,
        )
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        print("\n   Check your Snowflake credentials:")
        print(f"     SNOWFLAKE_ACCOUNT: {ACCOUNT}")
        print(f"     SNOWFLAKE_USER: {USER}")
        print(f"     SNOWFLAKE_ROLE: {ROLE}")
        print(f"     SNOWFLAKE_WAREHOUSE: {WAREHOUSE}")
        sys.exit(1)

    print("✅ Connected")
    cursor = conn.cursor()

    executed = 0
    failed = 0

    for i, sql in enumerate(SQL_STATEMENTS, 1):
        sql_clean = " ".join(sql.split())[:60]  # First 60 chars
        try:
            cursor.execute(sql)
            print(f"  [{i:2d}/{len(SQL_STATEMENTS)}] ✅ {sql_clean}...")
            executed += 1
        except Exception as e:
            print(f"  [{i:2d}/{len(SQL_STATEMENTS)}] ⚠️  {sql_clean}... ({str(e)[:40]})")
            failed += 1

    conn.close()

    print(f"\n{'='*70}")
    print(f"  Initialization complete: {executed} executed, {failed} warnings")
    print(f"{'='*70}")

    if failed == 0:
        print("\n✅ Snowflake platform is ready!")
        print("\n   Next steps:")
        print("     1. Run: python platform/scripts/health_check.py")
        print("     2. Connect your first Airbyte source in the web UI")
        print("     3. Run: platform add-source --name <source_name> --airbyte-connection-id <id>")
    else:
        print("\n⚠️  Some statements had warnings (likely already exist — this is OK)")


if __name__ == "__main__":
    init_snowflake()
